# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Allure setup

on:
  push:
    branches-ignore:
    - '!master'
    paths-ignore:
    - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B package --file pom.xml

#    - name: Publish to GitHub Packages Apache Maven
#      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
#      env:
#        GITHUB_TOKEN: ${{ github.token }}
    - name: run test
      run: mvn clean test -Dselenide.headless=true

    - name: Get Allure history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

#    - name: allure
#      run: allure generate target/allure-results -o target/allure-report

    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: target/allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
            PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PUBLISH_BRANCH: gh-pages
            PUBLISH_DIR: allure-history

#    - name: Post the link to the report
#      if: always()
#      uses: Sibz/github-status-action@v1
#      with:
#          authToken: ${{secrets.GITHUB_TOKEN}}
#          context: 'Test report'
#          state: 'success'
#          sha: ${{ github.event.pull_request.head.sha }}
#          target_url: simple-elf.github.io/github-allure-history/${{ github.run_number }}
#    - name: Get Allure history
#      uses: actions/checkout@v2
#      if: always()
#      continue-on-error: true
#      with:
#          ref: gh-pages
#          path: gh-pages
#    - name: Allure Report action from marketplace
#      uses: simple-elf/allure-report-action@master
#      if: always()
#      id: allure-report
#      with:
#          allure_results: target/allure-results
#          gh_pages: gh-pages
#          allure_report: allure-report
#          allure_history: allure-history

#    - name: Deploy report to Github Pages
#      if: always()
#      uses: peaceiris/actions-gh-pages@v2
#      env:
#          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          PUBLISH_BRANCH: gh-pages
#          PUBLISH_DIR: allure-history
